

class ForcError(Exception):
    pass

class IOError(ForcError):
    pass

